---
title: "erodyn_geomorphons_shapestats"
author: "fabian gruber"
date: "August 25, 2017"
output: html_document
---

```{r, include=FALSE}
require(rgdal)
geoms= c("flat","summit","ridge","shoulder","spur","slope","hollow","footslope","valley","depression")
mycols <- c("#e2e0e1","#000000","#c0262a","#d78321","#e7cb3c","#fcea0d","#bfd71c","#82b16b","#3e3ab8","#000000")

geomdf <- data.frame(geoms=geoms,col=mycols)
```

```{r,include=F}
folder="/home/fabs/Data/ERODYN_lenny/ERODYN_GIS/RData_stats2/"
Llist=c(3,10,15,20,25,30,40,50,75,100,125,150,200,250,400,1000)
filelist_fl1 <- list.files(folder,pattern="fl1\\.")
filelist_fl1 <- filelist_fl1[c(12,3,6,8,10,11,14,15,16,2,4,5,7,9,13,1)]
filelist_fl3 <- list.files(folder,pattern="fl3\\.")
filelist_fl3 <- filelist_fl3[c(12,3,6,8,10,11,14,15,16,2,4,5,7,9,13,1)]
filelist_fl5 <- list.files(folder,pattern="fl5\\.")
filelist_fl5 <- filelist_fl5[c(12,3,6,8,10,11,14,15,16,2,4,5,7,9,13,1)]
filelist_fl10 <- list.files(folder,pattern="fl10\\.")
filelist_fl10 <- filelist_fl10[c(12,3,6,8,10,11,14,15,16,2,4,5,7,9,13,1)]
filelist_fl15 <- list.files(folder,pattern="fl15\\.")
filelist_fl15 <- filelist_fl15[c(12,3,6,8,10,11,14,15,16,2,4,5,7,9,13,1)]
filelist_fl20 <- list.files(folder,pattern="fl20\\.")
filelist_fl20 <- filelist_fl20[c(12,3,6,8,10,11,14,15,16,2,4,5,7,9,13,1)]

```
##flatness threshold = 1 °
```{r,include=F}
featuresums_df <- data.frame(geoms)
areasums_df <- data.frame(geoms)
areamean_df <- data.frame(geoms)
areasd_df <- data.frame(geoms)
SImean_df <- data.frame(geoms)
SIsd_df <- data.frame(geoms)
MDmean_df <-data.frame(geoms)
MDsd_df <-data.frame(geoms)
for (f in filelist_fl1){
layer=unlist(strsplit(f,split=".RData"))
load(paste(folder,f,sep=""))
for (g in geoms){
areasums_df[areasums_df$geoms == as.character(g),as.character(layer)] <-ifelse(length(results[results$label == as.character(g),"area_sum"]) == 0,NA,results[results$label == as.character(g),"area_sum"])

featuresums_df[featuresums_df$geoms == as.character(g),as.character(layer)] <-ifelse(length(results[results$label == as.character(g),"featuresum"]) == 0,NA,results[results$label == as.character(g),"featuresum"])

areamean_df[areamean_df$geoms == as.character(g),as.character(layer)] <-ifelse(length(results[results$label == as.character(g),"area_mean"]) == 0,NA,results[results$label == as.character(g),"area_mean"])

areasd_df[areasd_df$geoms == as.character(g),as.character(layer)] <-ifelse(length(results[results$label == as.character(g),"area_sd"]) == 0,NA,results[results$label == as.character(g),"area_sd"])

SImean_df[SImean_df$geoms == as.character(g),as.character(layer)] <-ifelse(length(results[results$label == as.character(g),"SI_mean"]) == 0,NA,results[results$label == as.character(g),"SI_mean"])

SIsd_df[SIsd_df$geoms == as.character(g),as.character(layer)] <-ifelse(length(results[results$label == as.character(g),"SI_sd"]) == 0,NA,results[results$label == as.character(g),"SI_sd"])

MDmean_df[MDmean_df$geoms == as.character(g),as.character(layer)] <-ifelse(length(results[results$label == as.character(g),"MaxDist_mean"]) == 0,NA,results[results$label == as.character(g),"MaxDist_mean"])

MDsd_df[MDsd_df$geoms == as.character(g),as.character(layer)] <-ifelse(length(results[results$label == as.character(g),"MaxDist_sd"]) == 0,NA,results[results$label == as.character(g),"MaxDist_sd"])
}
}
```

```{r,echo=F}
df=featuresums_df
ylab="nr. of features"
main="nr. of features vs. search radius"
names(df) <- c("geoms",Llist)
plot(x=1,type="n",xlim=c(1,max(Llist)),ylim=c(min(df[,2:17],na.rm=T),max(df[,2:17],na.rm=T)),main=main,ylab=ylab,xlab="search radius")
legend("topright",lty=1,legend = geomdf$geoms,col=as.character(geomdf$col),ncol=3)
for (g in geoms){
try(lines(x=Llist,y=df[df$geoms == as.character(g),2:ncol(df)],col=as.character(geomdf[geomdf$geoms==as.character(g),"col"])))
}
```


```{r,echo=F}
df=areasums_df
ylab="total area in m²"
main="total area of landforms vs. search radius"
names(df) <- c("geoms",Llist)
plot(x=1,type="n",xlim=c(1,max(Llist)),ylim=c(min(df[,2:17],na.rm=T),max(df[,2:17],na.rm=T)),main=main,ylab=ylab,xlab="search radius")
legend("topright",lty=1,legend = geomdf$geoms,col=as.character(geomdf$col),ncol=3)
for (g in geoms){
try(lines(x=Llist,y=df[df$geoms == as.character(g),2:ncol(df)],col=as.character(geomdf[geomdf$geoms==as.character(g),"col"])))
}
```


```{r,echo=F}
df=areamean_df
ylab="mean size of features in m²"
main="mean size of features vs. search radius"
names(df) <- c("geoms",Llist)
plot(x=1,type="n",xlim=c(1,max(Llist)),ylim=c(min(df[,2:17],na.rm=T),max(df[,2:17],na.rm=T)),main=main,ylab=ylab,xlab="search radius")
legend("topright",lty=1,legend = geomdf$geoms,col=as.character(geomdf$col),ncol=3)
for (g in geoms){
try(lines(x=Llist,y=df[df$geoms == as.character(g),2:ncol(df)],col=as.character(geomdf[geomdf$geoms==as.character(g),"col"])))
}
```
