#!/usr/bin/python
# -*- coding: utf-8 -*-
# -*- encoding: utf-8 -*-
##################################needs grass7.0 with r.geomorphons-extension################
import os
dtm='dtm_50m_avg'
fl=15
Llist=[100,400]
#Llist=[3,10,15,20,25,30,40,50,75,100,125,150,200,250,400,1000]
Llist25m =[3,4,5,6,8,10,16,40]
Llist50m =[3,42,5,8,20]
skiplist = [0]
for L in Llist50m:
	for skip in skiplist:
		os.system('r.geomorphon dem=%s forms=geom_%s_L%im_fl%i_skip%i search=%i flat=%i skip=%i'%(dtm,dtm,L,fl,skip,L,fl,skip))
		os.system('r.to.vect input=geom_%s_L%im_fl%i_skip%i output=geom_%s_L%im_fl%i_skip%i type=area'%(dtm,L,fl,skip,dtm,L,fl,skip))
		os.system('v.out.ogr -e input=geom_%s_L%im_fl%i_skip%i output=/media/fabs/Volume/ERODYN/ERODYN_GIS/outshapes/geom_%s_L%im_fl%i_skip%i.shp'%(dtm,L,fl,skip,dtm,L,fl,skip))



#####################
import os
dtm='dtm'
fl=15
Llist=[100,400]
#Llist=[3,10,15,20,25,30,40,50,75,100,125,150,200,250,400,1000]
flatdistlist = [10,20,30,40,50,60,70,80,90]
for L in Llist:
	for flatdist in flatdistlist:
		os.system('r.geomorphon dem=%s forms=geom_%s_L%im_fl%i_flatdist%i search=%i flat=%i dist=%i'%(dtm,dtm,L,fl,flatdist,L,fl,flatdist))
		os.system('r.to.vect input=geom_%s_L%im_fl%i_flatdist%i output=geom_%s_L%im_fl%i_flatdist%i type=area'%(dtm,L,fl,flatdist,dtm,L,fl,flatdist))
		os.system('v.out.ogr -e input=geom_%s_L%im_fl%i_flatdist%i output=/media/fabs/Volume/ERODYN/ERODYN_GIS/outshapes/geom_%s_L%im_fl%i_flatdist%i.shp'%(dtm,L,fl,flatdist,dtm,L,fl,flatdist))

#####################
import os
dtm='dtm'
fl=15
Llist=[100,400]
#Llist=[3,10,15,20,25,30,40,50,75,100,125,150,200,250,400,1000]
flatdistlist = [10,20,30,40,50,60,70,80,90]
for L in Llist:
	for flatdist in flatdistlist:
		os.system('r.geomorphon dem=%s forms=geom_%s_L%im_fl%i_flatdist%i_skip%i search=%i flat=%i dist=%i skip=%i'%(dtm,dtm,L,fl,flatdist,flatdist,L,fl,flatdist,flatdist))
		os.system('r.to.vect input=geom_%s_L%im_fl%i_flatdist%i_skip%i output=geom_%s_L%im_fl%i_flatdist%i_skip%i type=area'%(dtm,L,fl,flatdist,flatdist,dtm,L,fl,flatdist,flatdist))
		os.system('v.out.ogr -e input=geom_%s_L%im_fl%i_flatdist%i_skip%i output=/media/fabs/Volume/ERODYN/ERODYN_GIS/outshapes/geom_%s_L%im_fl%i_flatdist%i_skip%i.shp'%(dtm,L,fl,flatdist,flatdist,dtm,L,fl,flatdist,flatdist))
